### ISSUE TITLE
Play and loop beginning/end

### ISSUE THREAD

**Issue by isedwards** [starplayerpc/starplayerpc#4]
Previously users created a series of videos - M1, M2, M3 where M1 was a one second loop at the start of a clip, M2 provided animation, and M3 was a one second loop at the end of the clip.

After adding a clip (containing M1+M2+M3) to the playlist, a user should be able to right-click and add a row above for the 1 second beginning loop and/or add a row below for the 1 second end loop.  The middle clip should be reduced accordingly.

Requires a menu to be displayed when right-clicking.

**Comment by Steve-Palmer** [comment]
It might be more general to implement this by specifying a start and end time for looping from within a longer clip. So looping the beginning would play 0 to 1 seconds, looping the end would be n-1 to n seconds. This could also be used to do longer loops (USA TV presenters like showing repeating loops of rain movement, this technique does not get used much by others, because it is intended to impress people with the professional tricks.). It would also enable the presenter to pause and loop in the middle of a long clip while talking, and then resume.
